# Generated by Django 6.0.5 on 2026-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordo',
            name='cobrancas',
            field=models.ManyToManyField(related_name='acordos', to='api.cobranca'),
        ),
    ]
